# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cheetah Style Guide
email: brad.stricker@hetras.com
description: > # this means to ignore newlines until "baseurl:"
  This is the intial development of the Hetras Style guide. 
  The design system will be called Cheetah Design System, 
  this comes from the famous saying that a cheetah never changes its spots. 
  There for our design system ensures that hetras never changes its style across brand elements.
baseurl: "/style-guide-guide" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: brad.strix
github_username:  bradstrix

# Build settings
markdown: kramdown
